# Here we'll store the necessary configuration parameters for the 
# source code of the tourism section of our implementation

# Name of experiment
exp_name: 'exp01_tourism'

### numOfOutboundTravellers: ###
#                               i) Number of out of bounds travellers
numOfOutboundTravellers: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/numberOfOutboundTravellers
# Output directory
output: /Users/dimitriosfotinos/Downloads/BOG/output