# Here we'll store the necessary configuration parameters for the 
# source code of the tourism section of our implementation

# Name of experiment
exp_name: 'exp01_tourism'

# 1) Number of out of bounds travellers (2022-2023)
# Greek Cizitens (Thousands)
numOfOutboundTravellers: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/numberOfOutboundTravellers

# 2) Reason of travel (2022-2023)
reasonOfTravel: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/reasonOfTravel

# 3) Income of travels (2022-2023)
# Milions of EU
incomeOfTravels: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/incomeOfTravels

# 4) Non-resident's overnight
# Thous. of overnight stays
overnightNonRes: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/overnightNonRes

# 5) Non Resident's expenses per Travel
# Euro
expPerTravelNR: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/expPerTravelNR

# Output directory
output: /Users/dimitriosfotinos/Downloads/BOG/output