# Here we'll store the necessary configuration parameters for the 
# source code of the tourism section of our implementation

# Name of experiment
exp_name: 'exp01_tourism'

# 1) Number of out of bounds travellers (2022-2023)
# Greek Cizitens (Thousands)
numOfOutboundTravellers: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/numberOfOutboundTravellers

# 2) Number of inbound traveller (2022-2023)
# Non-Greek Citizens (Thousands)
numOfInboundTravellers: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/numberOfInboundTravellers

# 3) Income of travels (2022-2023)
# Milions of EU

# 3) Reason of travel (2022-2023)
reasonOfTravel: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/reasonOfTravel

# 4) income of 

# Output directory
output: /Users/dimitriosfotinos/Downloads/BOG/output