# Here we'll store the necessary configuration parameters for the 
# source code of the tourism section of our implementation

# Name of experiment
exp_name: 'exp01_tourism'

# 1) Number of out of bounds travellers (2022-2023)
# Non-Greek Cizitens
numOfOutboundTravellers: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/numberOfOutboundTravellers

# 2) Number of inbound traveller (2022-2023)
numOfInboundTravellers: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/numberOfOutboundTravellers

# 3) Reason of travel (2022-2023)
reasonOfTravel: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/reasonOfTravel

# Output directory
output: /Users/dimitriosfotinos/Downloads/BOG/output