# Here we'll store the necessary configuration parameters for the 
# source code of the tourism section of our implementation

# Name of experiment
exp_name: 'exp01_tourism'

### 2022: ###
#             i) Number of out of bounds travellers

numOfOutboundTravellers22: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/2022/numberOfOutboundTravellers # i)

### 2021: ###
#             i) Number of out of bounds travellers
numOfOutboundTravellers21: /Users/dimitriosfotinos/Downloads/BOG/data/tourism/2021/numberOfOutboundTravellers # i)


# Output directory
output: /Users/dimitriosfotinos/Downloads/BOG/output